# Generated by Django 4.2.10 on 2024-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
