# Generated by Django 5.0.1 on 2024-02-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storage/images')),
                ('sluq', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('quantity_unit', models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('unit', 'шт')], max_length=20, verbose_name='Единица измерения (Количество)')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Лимит')),
                ('arrival_date', models.DateField(verbose_name='Дата прихода')),
                ('is_running_out', models.BooleanField(default=False, verbose_name='Заканчивающийся продукт')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Филиал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category')),
            ],
            options={
                'verbose_name_plural': 'Склад',
                'ordering': ['-arrival_date', 'name'],
            },
        ),
    ]
