# Generated by Django 4.2.10 on 2024-02-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('quantity_unit', models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('unit', 'шт')], max_length=20, verbose_name='Единица измерения (Количество)')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Лимит')),
                ('arrival_date', models.DateField(verbose_name='Дата прихода')),
                ('category', models.CharField(choices=[('ready_products', 'Готовые продукты'), ('raw_materials', 'Сырье')], max_length=20, verbose_name='Категория')),
                ('is_running_out', models.BooleanField(default=False, verbose_name='Заканчивающийся продукт')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name_plural': 'Склад',
                'ordering': ['-arrival_date', 'name'],
            },
        ),
    ]
