# Generated by Django 4.2.10 on 2024-02-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='limit_unit',
            field=models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('шт', 'шт')], default=1, max_length=20, verbose_name='Единица измерения (Количество)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Готовые продукты', 'Готовые продукты'), ('Сырье', 'Сырье')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_unit',
            field=models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('шт', 'шт')], max_length=20, verbose_name='Единица измерения (Количество)'),
        ),
    ]
