version: "3.12"

services:



  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
    - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn Neocafe24.wsgi:application -w 4 -b 0.0.0.0:8000"
    env_file:
      - .env

    networks:
      my_custom_network:
        ipv4_address: 172.20.0.5

  networks:
    my_custom_network:
      driver: bridge