# Generated by Django 4.2.10 on 2024-03-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_image_branch_image_1_branch_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='NeoCafe', max_length=100, unique=True),
        ),
    ]
