# Generated by Django 4.2.10 on 2024-03-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='image_1',
            new_name='image',
        ),
    ]
