# Generated by Django 4.2.10 on 2024-02-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images', verbose_name='Фото блюда')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='branches.branch', verbose_name='Филиал')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_extra_product', models.CharField(choices=[['Milk', 'Молоко'], ['Syrop', 'Сиропы']], max_length=20, null=True, verbose_name='Доп. Продукт')),
                ('name', models.CharField(max_length=100, verbose_name='Название доп. продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('choice_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_products', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Доп. Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='menu_catego_name_dba8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['id', 'slug'], name='menu_menu_id_c6debc_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='menu_menu_name_4933c0_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-created'], name='menu_menu_created_8af8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='extraitem',
            index=models.Index(fields=['name'], name='menu_extrai_name_315e3d_idx'),
        ),
    ]
