# Generated by Django 4.2.10 on 2024-02-28 23:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Выпечка', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement_unit', models.CharField(choices=[('гр', 'гр'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images', verbose_name='Фото блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='branches.branch', verbose_name='Филиал')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menu'),
        ),
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_extra_product', models.CharField(choices=[('Milk', 'Молоко'), ('Syrup', 'Сиропы')], max_length=20, null=True, verbose_name='Доп. Продукт')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название доп. продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('choice_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_products', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Доп. Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='menu_menu_name_4933c0_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-created'], name='menu_menu_created_8af8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='extraitem',
            index=models.Index(fields=['name'], name='menu_extrai_name_315e3d_idx'),
        ),
    ]
