# Generated by Django 4.2.10 on 2024-02-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name_plural': 'Состав блюда'},
        ),
        migrations.RemoveIndex(
            model_name='extraitem',
            name='menu_extrai_name_315e3d_idx',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
