# Generated by Django 4.2.10 on 2024-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images', verbose_name='Фото блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_type',
            field=models.CharField(choices=[('Готовые продукты', 'Готовые продукты'), ('Сырье', 'Сырье')], default=1, max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
