# Generated by Django 4.2.10 on 2024-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_image_menu_meal_type_alter_menu_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_type',
            field=models.CharField(choices=[('Готовые продукты', 'Готовые продукты'), ('Сырье', 'Сырье')], max_length=20, verbose_name='Тип блюда'),
        ),
    ]
