# Generated by Django 4.2.10 on 2024-03-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitemingredient_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient'),
        ),
    ]
