# Generated by Django 4.2.10 on 2024-03-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitemingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('гр', 'гр'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
            preserve_default=False,
        ),
    ]
