# Generated by Django 4.2.10 on 2024-03-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('гр', 'гр'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
