# Generated by Django 4.2.10 on 2024-03-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal_type',
        ),
    ]
