# Generated by Django 4.2.10 on 2024-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_extraitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='type_extra_product',
            field=models.CharField(choices=[('Молоко', 'Молоко'), ('Сироп', 'Сиропы')], max_length=20, null=True, verbose_name='Доп. Продукт'),
        ),
    ]
