# Generated by Django 4.2.10 on 2024-03-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_extraitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraitem',
            name='quantity',
        ),
    ]
