# Generated by Django 4.2.10 on 2024-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_extraitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
