# Generated by Django 4.2.10 on 2024-03-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_extraitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraitem',
            name='quantity',
        ),
    ]
