# Generated by Django 4.2.10 on 2024-03-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_extraitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
