# Generated by Django 4.2.10 on 2024-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('На вынос', 'На вынос'), ('В заведении', 'В заведении')], default='На вынос', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Готово', 'Готово'), ('Отменено', 'Отменено'), ('Завершено', 'Завершено')], default='Новый', max_length=20),
        ),
    ]
