# Generated by Django 4.2.10 on 2024-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dine_in',
            field=models.BooleanField(default=False, verbose_name='Заказ в ресторане'),
        ),
    ]
