# Generated by Django 4.2.10 on 2024-03-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_dine_in',
        ),
    ]
