# Generated by Django 4.2.10 on 2024-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_table_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_quantity',
            new_name='order_quantity',
        ),
    ]
