# Generated by Django 4.2.10 on 2024-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_menu_quantity_orderitem_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_quantity',
            new_name='quantity',
        ),
    ]
