# Generated by Django 4.2.10 on 2024-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_completed_at_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='extra_product_quantity',
        ),
    ]
