# Generated by Django 4.2.10 on 2024-03-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_extraitem_quantity'),
        ('orders', '0011_remove_orderitem_extra_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemExtraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.extraitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
        ),
    ]
