# Generated by Django 4.2.10 on 2024-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitemextraproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
