# Generated by Django 4.2.10 on 2024-04-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='staff_member',
        ),
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
