# Generated by Django 4.2.10 on 2024-04-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='position',
        ),
    ]
