# Generated by Django 4.2.10 on 2024-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='table',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
