# Generated by Django 4.2.10 on 2024-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='table',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
